### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-manifests#12]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@maurezen thank you for the ticket reported, I topped your account for 15 mins, transaction `49998827`

**Comment by dmarkov** [comment]
@romankisilenko this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by RomanKisilenko** [comment]
@dmarkov, is this a right place to ask for help or do you have some specific process to be followed? It looks like I'm missing permissions to write to repository, thus I'm not able to commit and create a pull request. Could somebody please provide me permissions to this and other repositories I will work on.

**Comment by yegor256** [comment]
@RomanKisilenko you don't need to commit/push to this repo. Instead, we're working via pull request. More info here: http://www.yegor256.com/2014/04/15/github-guidelines.html

**Comment by RomanKisilenko** [comment]
This is what I'm getting on commit attempt:
```
ip-192-168-3-104:jcabi-manifests roman$ git branch
* 12
  master
ip-192-168-3-104:jcabi-manifests roman$ git remote -v
origin	git@github.com:jcabi/jcabi-manifests.git (fetch)
origin	git@github.com:jcabi/jcabi-manifests.git (push)
ip-192-168-3-104:jcabi-manifests roman$ git push origin 12
ERROR: Permission to jcabi/jcabi-manifests.git denied to RomanKisilenko.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by RomanKisilenko** [comment]
@maurezen PR was reviewed and closed, please close this issue.

**Comment by dmarkov** [comment]
@romankisilenko **30 mins** added to your account (payment number `50616178`), many thanks for your contribution!. added +30 to your rating, now it is equal to +240
