### ISSUE TITLE
Wrong artifact version in http://manifests.jcabi.com documentation

### ISSUE THREAD

**Issue by RomanKisilenko** [jcabi/jcabi-manifests#13]
http://manifests.jcabi.com lists 1.0-SNAPSHOT as the latest snapshot version, should be 2.0-SNAPSHOT. Not sure if this should be considered a bug or not.

**Comment by yegor256** [comment]
@RomanKisilenko definitely a bug, thanks

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@romankisilenko this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by RomanKisilenko** [comment]
@dmarkov, Who can explain the release process to me? Since it will be necessary to alter this version on every release I need to understand if it is possible to automate setting this version, e.g. on rultor release.

**Comment by yegor256** [comment]
@RomanKisilenko I'll try to explain it tomorrow

**Comment by dmarkov** [comment]
@romankisilenko thank you for the ticket reported, I topped your account for 15 mins, transaction `50342789`

**Comment by RomanKisilenko** [comment]
PR reviewed and closed, so closing this issue as well.

**Comment by dmarkov** [comment]
@romankisilenko done, I added **30 mins** in payment `50616196`... +30 added to your rating, at the moment it is: +300
