### ISSUE TITLE
pom.xml:106-107: Remove this declaration when parent...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-manifests#20]
Puzzle `16-4036a3b3` in `pom.xml:106-107` has to be resolved: Remove this declaration when parent pom would fix issue jcabi/jcabi-parent#19... The puzzle was created by maurezen on 14-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@maurezen the issue is yours, please help

**Comment by maurezen** [comment]
@yegor256 @dmarkov I depend on the issue jcabi/jcabi#297 here. Waiting for it to be resolved.

**Comment by maurezen** [comment]
@yegor256 any comments? do you approve the dependency?

**Comment by yegor256** [comment]
@dmarkov we just need more time here

**Comment by dmarkov** [comment]
> @dmarkov we just need more time here

@yegor256 no problem, thanks for letting me know

**Comment by yegor256** [comment]
@maurezen FYI https://github.com/jcabi/jcabi/issues/297 is closed already, you can continue here

**Comment by maurezen** [comment]
@yegor256 @dmarkov Created a pull request here #21 , please get someone review it.

**Comment by maurezen** [comment]
@dmarkov #21 has been merged, please close the issue.

**Comment by dmarkov** [comment]
Finished, thanks, closing..

**Comment by dmarkov** [comment]
@maurezen Much appreciated! **30 mins** was added to your account, payment ID `54987112`, time spent is 1629 hours and 32 mins. +30 added to your rating, at the moment it is: [+1327](http://www.netbout.com/b/35102?open=rating)
