### ISSUE TITLE
Lack of language level restrictions in the pom

### ISSUE THREAD

**Issue by westonized** [jcabi/jcabi-manifests#36]
Problem: Build servers build against Java 1.7
Lack of language restriction in POM means that locally Java 1.8 is acceptable and it is not apparent until we start PR that we have used some Java 8 method/class.

The ide and local build should restrict language use, the simplest way would be to include this in the POM.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by westonized** [comment]
@dmarkov what's happening with this task?

**Comment by yegor256** [comment]
@westonized our JDK version is 1.6 and inherit that from jcabi-parent POM. I don't think we should duplicate that information in our own POM. or I didn't understand the question?

**Comment by westonized** [comment]
@yegor256 If it is inherited, how come I have no issues building against java 1.8 features and methods locally. And I only discover it's a problem when I start a pull request.

**Comment by westonized** [comment]
@yegor256 It looks like you have done what this task is suggesting anyway in the pom here: bc4391c9c969c75d6339b0a1dbac6ed53354a873

**Comment by yegor256** [comment]
@westonized OK, I'm closing. thanks.
