### ISSUE TITLE
Configure puzzle format validation in .travis.yml and .rultor.yml

### ISSUE THREAD

**Issue by westonized** [jcabi/jcabi-manifests#37]
Puzzle format is not validated on Travis build. For example I have some badly formatted `@todo`s in #35 

Configure `pdd` and `est` in.travis.yml as done in https://github.com/jcabi/jcabi-xml/blob/master/.travis.yml
and https://github.com/jcabi/jcabi-xml/blob/master/.rultor.yml

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by westonized** [comment]
@dmarkov what's happening with this task?

**Comment by yegor256** [comment]
@westonized fixed in bc4391c thanks!

**Comment by westonized** [comment]
@yegor256 please explain invalid label, did I raise this incorrectly?

**Comment by yegor256** [comment]
@westonized you did everything correct, but check this out: http://at.teamed.io/policy.html#13

**Comment by westonized** [comment]
> §36 You may ask a project manager to mark any ticket as invalid or duplicate, just say something like “this is invalid” or “this is duplicate”.

OK, but that doesn't explain "invalid", and if it just means what I might assume it means, i.e. "this issue is not valid" then why was it fixed?
