### ISSUE TITLE
jcabi-manifests support jakarta?

### ISSUE THREAD

**Issue by Wade-tech** [jcabi/jcabi-manifests#59]
Hi  which jcabi-manifests version support jakarta?

**Comment by melbeltagy** [comment]
Apparently, none. 
I've spent 5 hours investigating why my code doesn't work after upgrading to spring boot 3.0.x and finally found out that this library is the reason 😆 

Navigating the code-base, I found this: comment in the pom.xml:
https://github.com/jcabi/jcabi-manifests/blob/master/pom.xml#L71-L75

**Comment by melbeltagy** [comment]
The current releases does not support Jakarta EE yet.

I have created this PR: https://github.com/jcabi/jcabi-manifests/pull/60 to support Jakarta EE
